<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ThreeDGodCreator.Core.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\3DGodCreator.Core\3DGodCreator.Core.csproj" />
    <ProjectReference Include="..\src\ThreeDGod.Application\ThreeDGod.Application.csproj" />
    <ProjectReference Include="..\src\ThreeDGod.Infrastructure\ThreeDGod.Infrastructure.csproj" />
    <ProjectReference Include="..\src\ThreeDGod.Core\ThreeDGod.Core.csproj" />
    <ProjectReference Include="..\src\ThreeDGod.Persistence\ThreeDGod.Persistence.csproj" />
  </ItemGroup>

</Project>
