<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ThreeDGodCreator.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx" />
    <EmbeddedResource Update="Resources\Strings.de.resx">
      <DependentUpon>Strings.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
